name: Test

on:
  repository_dispatch:
  workflow_dispatch:

permissions:
  contents: write  # 写入仓库内容
  pull-requests: write  # 创建/修改 PR

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Organize files
      id: organize
      run: |
        cd openwrt/bin/targets/*/*
        rm -rf packages
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT
      # 添加 continue-on-error 确保后续步骤能获取到状态
      continue-on-error: true

    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@v1.0.0
      if: steps.organize.outputs.status != 'success'
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        